"""Rasterize the pinned Lucide weather SVGs for the LVGL header.

Requires rsvg-convert and Pillow. Run from the repository root.
"""

from io import BytesIO
from pathlib import Path
import subprocess

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "firmware" / "weather_assets"
OUTPUT = ROOT / "firmware" / "weather_icons.h"
SIZE = 28
COLORS = {
    "sun": "#FFD36A",
    "moon": "#DCE7FF",
    "cloud-sun": "#FFD36A",
    "cloud-moon": "#DCE7FF",
    "cloud": "#EAF2FF",
    "cloud-fog": "#EAF2FF",
    "cloud-drizzle": "#78D9FF",
    "cloud-rain": "#78D9FF",
    "cloud-sun-rain": "#78D9FF",
    "cloud-moon-rain": "#78D9FF",
    "cloud-snow": "#EAF2FF",
    "cloud-lightning": "#FFD36A",
}


def rasterize(name: str, color: str) -> Image.Image:
    svg = (ASSETS / f"{name}.svg").read_text()
    assert 'stroke="currentColor"' in svg and 'stroke-width="2"' in svg
    svg = svg.replace('stroke="currentColor"', f'stroke="{color}"')
    svg = svg.replace('stroke-width="2"', 'stroke-width="2.3"')
    rendered = subprocess.run(
        ["rsvg-convert", "--width", str(SIZE), "--height", str(SIZE)],
        input=svg.encode(), capture_output=True, check=True
    ).stdout
    return Image.open(BytesIO(rendered)).convert("RGBA")


def descriptor(name: str, image: Image.Image) -> str:
    name = name.replace("-", "_")
    # LVGL ARGB8888 stores pixels in BGRA byte order on the ESP32 and native tests.
    raw = bytearray()
    for r, g, b, a in image.getdata():
        raw.extend((b, g, r, a))
    chunks = [",".join(map(str, raw[i:i + 48])) for i in range(0, len(raw), 48)]
    body = ",\n".join(chunks)
    return (
        f"inline const uint8_t weather_{name}_pixels[] = {{\n{body}\n}};\n"
        f"inline const lv_image_dsc_t weather_{name}_icon = [] {{\n"
        f"  lv_image_dsc_t d{{}}; d.header.magic=LV_IMAGE_HEADER_MAGIC;\n"
        f"  d.header.cf=LV_COLOR_FORMAT_ARGB8888; d.header.w={SIZE}; d.header.h={SIZE};\n"
        f"  d.header.stride={SIZE * 4}; d.data_size=sizeof(weather_{name}_pixels);\n"
        f"  d.data=weather_{name}_pixels; return d;\n"
        f"}}();\n"
    )


def main() -> None:
    images = {name: rasterize(name, color) for name, color in COLORS.items()}
    for name, image in images.items():
        image.save(ASSETS / f"{name}.png")
    source = (
        "// Generated by scripts/generate_weather_icons.py from pinned Lucide SVGs.\n"
        "// See weather_assets/LUCIDE-LICENSE and weather_assets/README.md.\n"
        "#pragma once\n#include \"lvgl.h\"\nnamespace lcars {\n"
        + "\n".join(descriptor(name, image) for name, image in images.items())
        + "}\n"
    )
    OUTPUT.write_text(source)


if __name__ == "__main__":
    main()
